apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region:  us-east-2   
    objects: | 
      - objectName: dev/nodejsapp-secret
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: db_username 
          - path: password 
            objectAlias: db_password
  secretObjects:
  - secretName: k8s-secret
    type: Opaque
    data:
    - objectName: db_username
      key: username
    - objectName: db_password
      key: password